import { Inter } from 'next/font/google'
import './globals.css'
import { LIGHT_TOKENS, DARK_TOKENS } from '@/constants'
import Header from '@/components/Header'
import Sidebar from '@/components/Sidebar'
import "the-new-css-reset/css/reset.css"

import localFont from 'next/font/local'


const newKansas = localFont({
    src: './font/newKansas/NewKansasTRIAL-SemiBold.otf',
})


const Roobert = localFont({
    src: [
        {
            path: './font/roobert/RoobertTRIAL-Regular.otf',
            weight: '400',
            style: 'normal',
        },
        {
            path: './font/roobert/RoobertTRIAL-Bold.otf',
            weight: '500',
            style: 'normal',
        },
    ],
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

    const theme = "dark"

    return (
        <html lang="en" style={theme == 'light' ? LIGHT_TOKENS : DARK_TOKENS}>
            <body className={Roobert.className}>
                <Header theme={theme} />
                <Sidebar />
                <main>{children}</main>
            </body>
        </html>
    )
}
